#!/bin/bash

echo "================================================"
echo "CONFIGURAR UPSTASH REDIS EN VERCEL"
echo "================================================"
echo ""
echo "1. Ve a: https://console.upstash.com/login"
echo "2. Crea una cuenta (gratis)"
echo "3. Create Database → Regional → us-east-1"
echo "4. Copia las credenciales REST API"
echo ""
echo "Luego ejecuta estos comandos (reemplaza con tus valores):"
echo ""
echo "vercel env add UPSTASH_REDIS_REST_URL production --value 'https://TU-INSTANCIA.upstash.io' --yes"
echo "vercel env add UPSTASH_REDIS_REST_TOKEN production --value 'TU-TOKEN-AQUI' --yes"
echo ""
echo "Después, redeploy:"
echo "vercel --prod --yes"
echo ""
echo "================================================"
